<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>RegistroMs.Api</RootNamespace>
    <AssemblyName>RegistroMs.Api</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Services\Auth\Auth.Application\Auth.Application.csproj" />
    <ProjectReference Include="..\Services\Auth\Auth.Infrastructure\Auth.Infrastructure.csproj" />
    <ProjectReference Include="..\Services\Estudiantes\Estudiantes.Application\Estudiantes.Application.csproj" />
    <ProjectReference Include="..\Services\Estudiantes\Estudiantes.Infrastructure\Estudiantes.Infrastructure.csproj" />
    <ProjectReference Include="..\Services\Programas\Programas.Application\Programas.Application.csproj" />
    <ProjectReference Include="..\Services\Programas\Programas.Infrastructure\Programas.Infrastructure.csproj" />
    <ProjectReference Include="..\Services\Catalogo\Catalogo.Application\Catalogo.Application.csproj" />
    <ProjectReference Include="..\Services\Catalogo\Catalogo.Infrastructure\Catalogo.Infrastructure.csproj" />
    <ProjectReference Include="..\Services\Inscripciones\Inscripciones.Application\Inscripciones.Application.csproj" />
    <ProjectReference Include="..\Services\Inscripciones\Inscripciones.Infrastructure\Inscripciones.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

</Project>
