FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY . .
RUN dotnet restore registro-ms/RegistroMs.Api/RegistroMs.Api.csproj
RUN dotnet publish registro-ms/RegistroMs.Api/RegistroMs.Api.csproj -c Release -o /app

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app .
ENV ASPNETCORE_URLS=http://+:8080
ENTRYPOINT ["dotnet", "RegistroMs.Api.dll"]
